version: '3'
services:
  jvs-knowledge-ui:
    build:
      context: .
    restart: always
    container_name: registry.cn-chengdu.aliyuncs.com/jvs-tree/jvs-ui
    image: jvs-ui
    networks:
      - jvs_jvs
    external_links:
      - gateway
    ports:
      - 8080:80

networks:
  jvs_jvs:
    external: true
